//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÁguaPrivadaMatanquene
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MatanqueneEntities : DbContext
    {
        public MatanqueneEntities()
            : base("name=MatanqueneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<clienteDetails_Result> clienteDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<clienteDetails_Result>("clienteDetails");
        }
    
        public virtual ObjectResult<Nullable<decimal>> divida(Nullable<int> cLIENTE)
        {
            var cLIENTEParameter = cLIENTE.HasValue ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("divida", cLIENTEParameter);
        }
    
        public virtual ObjectResult<escalaoDetails_Result> escalaoDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<escalaoDetails_Result>("escalaoDetails");
        }
    
        public virtual ObjectResult<factura_Result> factura()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<factura_Result>("factura");
        }
    
        public virtual ObjectResult<facturacao_Result> facturacao(Nullable<int> cLIENTE)
        {
            var cLIENTEParameter = cLIENTE.HasValue ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<facturacao_Result>("facturacao", cLIENTEParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> multa(Nullable<int> cLIENTE)
        {
            var cLIENTEParameter = cLIENTE.HasValue ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("multa", cLIENTEParameter);
        }
    
        public virtual ObjectResult<DEBITO_Result> DEBITO(Nullable<int> cLIENTE)
        {
            var cLIENTEParameter = cLIENTE.HasValue ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DEBITO_Result>("DEBITO", cLIENTEParameter);
        }
    }
}
